r"""
generated by json2python-models v0.3.0 at Wed Jan 25 03:36:22 2023
command: /Users/weloxd/Documents/PythonWorkspace/DiforceTelegramBot/venv/lib/python3.10/site-packages/json_to_models/__main__.py -m GoodModel /Users/weloxd/Documents/PythonWorkspace/DiforceTelegramBot/models/good.json -f attrs
"""
import attr


@attr.s
class GoodModel:
    name: str = attr.ib()
    article_num: str = attr.ib()
    base_measure_unit: str = attr.ib()
    comment: str = attr.ib()
    good_set: str = attr.ib()
    general_image: str = attr.ib()
    general_supplier: str = attr.ib()
    manufacturer: str = attr.ib()
    price_group: str = attr.ib()
    color: str = attr.ib()

