r"""
generated by json2python-models v0.3.0 at Wed Jan 25 02:53:14 2023
command: /Users/weloxd/Documents/PythonWorkspace/DiforceTelegramBot/venv/lib/python3.10/site-packages/json_to_models/__main__.py -m UserModel /Users/weloxd/Documents/PythonWorkspace/DiforceTelegramBot/models/user.json -f attrs
"""
import attr
from typing import Any, List


@attr.s
class UserModel:
    tgid: int = attr.ib()
    username: str = attr.ib()
    fullname: str = attr.ib()
    is_admin: bool = attr.ib()
    balance: int = attr.ib()
    cart: List[Any] = attr.ib()
    created_at: str = attr.ib()

